apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: chinthy2/devops-k8s
          ports:
            - containerPort: 5000
          env:
            - name: devops-k8s-env
              value: development
            - name: devops-k8s
              value: app.py
